<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="rspec" tests="1" skipped="0" failures="1" errors="0" time="0.020041" timestamp="2019-12-26T23:42:01+09:00" hostname="masayukinoMacBook-puro.local">
<properties>
<property name="seed" value="1816"/>
</properties>
<testcase classname="spec.models.ci_cutomize_spec" name="CIの強制判定 ci_successの場合はテストに失敗すること" file="./spec/models/ci_cutomize_spec.rb" time="0.017545"><failure message="expected: truthy value
     got: false" type="RSpec::Expectations::ExpectationNotMetError">Failure/Error: expect(false).to be_truthy

  expected: truthy value
       got: false
./spec/models/ci_cutomize_spec.rb:12:in `block (2 levels) in &lt;top (required)&gt;&apos;</failure></testcase>
</testsuite>
